### ISSUE TITLE
WheelValidationError of torch package when running poetry install

### ISSUE THREAD

**Issue by StoneT2000** [vwxyzjn/cleanrl#367] opened 2023-03-27 21:37 UTC
## Problem Description
I'm trying setup the dev environment for this repo.

When running poetry install I get the following

```
  • Installing torch (1.12.1): Failed

  _WheelFileValidationError

  ["In /home/stao/.cache/pypoetry/artifacts/7f/2e/2d/980d8e9c948cda527927def0ef21d60010410b8db138a849111a08e8bf/torch-1.12.1-cp39-cp39-manylinux1_x86_64.whl, hash / size of torch-1.12.1.dist-info/METADATA didn't match RECORD"]
```

## Checklist
- [x] I have installed dependencies via `poetry install` (see [CleanRL's installation guideline](https://docs.cleanrl.dev/get-started/installation/). (n/a)
- [x] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo.
- [x] I have checked the [documentation site](https://docs.cleanrl.dev/) and found not relevant information in [GitHub issues](https://github.com/vwxyzjn/cleanrl/issues).

## Expected Behavior
Torch should install and poetry install shouldn't complain?

## Steps to Reproduce
Clean fork of this repo, running python3.9 and running `poetry install`.

**Comment by vwxyzjn** [comment] 2023-03-27 21:37
Duplicate of #365. Please downgrade poetry.

**Closed** 2023-03-27 21:38 UTC
